#!/bin/bash

#Custermize this for your application
BIN_DIR=bin
ARM_BIN_DIR=arm/bin
OPENOCD_BIN_DIR=openocd/bin
OPENOCD_SHARE_DIR=openocd/share
LIBUSB_COMPAT_DIR=libusb-compat
LIBUSB_COMPAT_INCLUDE_DIR=libusb-compat/include
LIBUSB_COMPAT_BIN_DIR=libusb-compat/bin
LIBUSB_DIR=libusb
LIBUSB_INCLUDE_DIR=libusb/include

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcuts to /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${BIN_DIR}/* /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${ARM_BIN_DIR}/* /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${OPENOCD_BIN_DIR}/* /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${LIBUSB_COMPAT_BIN_DIR}/* /usr/local/bin

#Sharing is caring
ln -s -f ${PRODUCT_HOME}/${OPENOCD_SHARE_DIR} /usr/local/share/openocd

#Include
ln -s -f ${PRODUCT_HOME}/${LIBUSB_COMPAT_INCLUDE_DIR} /usr/local/include/libusb-compat
ln -s -f ${PRODUCT_HOME}/${LIBUSB_INCLUDE_DIR} /usr/local/include/libusb

#Opt
ln -s -f ${PRODUCT_HOME}/${LIBUSB_COMPAT_DIR} /usr/local/opt/libusb-compat
ln -s -f ${PRODUCT_HOME}/${LIBUSB_DIR} /usr/local/opt/libusb

echo "Post installation process finished"
