#!/bin/bash

#Custermize this for your application
BIN_DIR=bin
ARM_BIN_DIR=arm/bin
OPENOCD_BIN_DIR=openocd/bin
OPENOCD_SHARE_DIR=openocd/share

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcuts to /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${BIN_DIR}/* /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${ARM_BIN_DIR}/* /usr/local/bin
ln -s -f ${PRODUCT_HOME}/${OPENOCD_BIN_DIR}/* /usr/local/bin

#Sharing is caring
ln -s -f ${PRODUCT_HOME}/${OPENOCD_SHARE_DIR} /usr/local/share/openocd

echo "Post installation process finished"
